# Generated by Django 5.1.1 on 2024-11-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='time')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Poster')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Clubs.clubs', verbose_name='Club')),
            ],
        ),
    ]
