# Generated by Django 5.1.1 on 2024-11-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Club name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Clubs/', verbose_name='Club Image')),
            ],
        ),
    ]
